# -*- coding: utf-8 -*-
"""Paula_Ulloa_ FPY1101_005V

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwyPbDsa6Q1o1DJjOByxddm-I8wqAWPG
"""

import json

from datetime import datetime



ventas = []



precios_pizzas = {

  "margarita": {"pequeña": 5500, "mediana": 8500, "familiar": 11000},

  "mexicana": {"pequeña": 7000, "mediana": 10000, "familiar": 13000},

  "barbacoa": {"pequeña": 6500, "mediana": 9500, "familiar": 12500},

  "vegetariana": {"pequeña": 5000, "mediana": 8000, "familiar": 10500}

}



def menu():

  print("\n--- Sistema de Ventas de Pizzas ---")

  print("1. Registrar una venta")

  print("2. Mostrar todas las ventas")

  print("3. Buscar ventas por cliente")

  print("4. Guardar las ventas en un archivo")

  print("5. Cargar las ventas desde un archivo")

  print("6. Generar una boleta")

  print("7. Anular venta")

  print("8. Salir")

  opcion = input("Seleccione una opción: ")

  return opcion



def registrar_venta():

  nombre_cliente = input("Nombre del cliente: ")

  tipo_cliente = input("Tipo de cliente (diurno/vespertino/administrativo): ").lower()

  tipo_pizza = input("Tipo de pizza (margarita/mexicana/barbacoa/vegetariana): ").lower()

  tamaño_pizza = input("Tamaño de la pizza (pequeña/mediana/familiar): ").lower()

  cantidad = int(input("Cantidad de pizzas: "))



  if tipo_pizza not in precios_pizzas or tamaño_pizza not in precios_pizzas[tipo_pizza]:

    print("Tipo o tamaño de pizza inválido.")

    return



  precio_unitario = precios_pizzas[tipo_pizza][tamaño_pizza]



  descuento = 0

  if tipo_cliente == 'diurno':

    descuento = 0.15

  elif tipo_cliente == 'vespertino':

    descuento = 0.18

  elif tipo_cliente == 'administrativo':

    descuento = 0.11



  precio_total = precio_unitario * cantidad

  precio_final = precio_total * (1 - descuento)



  fecha_hora = datetime.now().strftime("%Y-%m-%d %H:%M:%S")



  venta = {

    "fecha_hora": fecha_hora,

    "nombre_cliente": nombre_cliente,

    "tipo_cliente": tipo_cliente,

    "tipo_pizza": tipo_pizza,

    "tamaño_pizza": tamaño_pizza,

    "cantidad": cantidad,

    "precio_unitario": precio_unitario,

    "precio_total": precio_total,

    "descuento": descuento,

    "precio_final": precio_final

  }

  ventas.append(venta)

  print(f"\nVenta registrada:\n")

  print(f"Fecha y hora: {fecha_hora}")

  print(f"Cliente: {nombre_cliente}")

  print(f"Tipo de cliente: {tipo_cliente}")

  print(f"Tipo de pizza: {tipo_pizza}")

  print(f"Tamaño de pizza: {tamaño_pizza}")

  print(f"Cantidad: {cantidad}")

  print(f"Precio unitario: {precio_unitario}")

  print(f"Precio total: {precio_total}")

  print(f"Descuento aplicado: {descuento * 100}%")

  print(f"Precio final: {precio_final}")



def mostrar_ventas():

  if not ventas:

    print("No hay ventas registradas.")

  else:

    for venta in ventas:

      print("\n--- Detalles de la Venta ---")

      print(f"Fecha y hora: {venta['fecha_hora']}")

      print(f"Cliente: {venta['nombre_cliente']}")

      print(f"Tipo de cliente: {venta['tipo_cliente']}")

      print(f"Tipo de pizza: {venta['tipo_pizza']}")

      print(f"Tamaño de pizza: {venta['tamaño_pizza']}")

      print(f"Cantidad: {venta['cantidad']}")

      print(f"Precio unitario: {venta['precio_unitario']}")

      print(f"Precio total: {venta['precio_total']}")

      print(f"Descuento aplicado: {venta['descuento'] * 100}%")

      print(f"Precio final: {venta['precio_final']}")



def buscar_ventas():

  nombre_cliente = input("Ingrese el nombre del cliente a buscar: ")

  ventas_cliente = [venta for venta in ventas if venta["nombre_cliente"] == nombre_cliente]



  if not ventas_cliente:

    print(f"No se encontraron ventas para el cliente {nombre_cliente}.")

  else:

    for venta in ventas_cliente:

      print("\n--- Detalles de la Venta ---")

      print(f"Fecha y hora: {venta['fecha_hora']}")

      print(f"Cliente: {venta['nombre_cliente']}")

      print(f"Tipo de cliente: {venta['tipo_cliente']}")

      print(f"Tipo de pizza: {venta['tipo_pizza']}")

      print(f"Tamaño de pizza: {venta['tamaño_pizza']}")

      print(f"Cantidad: {venta['cantidad']}")

      print(f"Precio unitario: {venta['precio_unitario']}")

      print(f"Precio total: {venta['precio_total']}")

      print(f"Descuento aplicado: {venta['descuento'] * 100}%")

      print(f"Precio final: {venta['precio_final']}")



def guardar_ventas():

  with open('ventas.json', 'w') as file:

    json.dump(ventas, file, indent=4)

  print("Ventas guardadas en 'ventas.json'.")



def cargar_ventas():

  global ventas

  try:

    with open('ventas.json', 'r') as file:

      ventas = json.load(file)

    print("Ventas cargadas desde 'ventas.json'.")

  except FileNotFoundError:

    print("No se encontró el archivo 'ventas.json'.")



def generar_boleta():

  index = int(input("\nIngrese el índice de la venta para generar boleta: "))

  if 0 <= index < len(ventas):

    venta = ventas[index]

    print("\n--- Boleta ---")

    print(f"Fecha: {venta['fecha_hora']}")

    print(f"Cliente: {venta['cliente']}")

    print(f"Pizza: {venta['tipo_pizza']} {venta['tamaño']}")

    print(f"Cantidad: {venta['cantidad']}")

    print(f"Precio unitario: ${venta['precio_unitario']}")

    print(f"Descuento: {venta['descuento']*100}%")

    print(f"Total: ${venta['precio_total']}")

  else:

    print("Índice de venta no válido.")



def main():

  while True:

    opcion = menu()

    if opcion == '1':

      registrar_venta()

    elif opcion == '2':

      mostrar_ventas()

    elif opcion == '3':

      buscar_ventas()

    elif opcion == '4':

      guardar_ventas()

    elif opcion == '5':

      cargar_ventas()

    elif opcion == '6':
      generar_boleta()

    elif opcion == "7":
      print("Venta anulada")

    elif opcion == "8":
      print("Saliendo del programa.")

      break

    else:

      print("Opción no válida. Intente de nuevo.")



if __name__ == "__main__":

  main()

